#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/."
fi

CLJSC_CP=''
for next in $DIR/../cljs $DIR/../lib/* $DIR/../src $DIR/../libclojurescript.jar; do
    CLJSC_CP=$CLJSC_CP:$next
done

if command -v rlwrap >/dev/null 2>&1; then
    JCMD="java"
else
    JCMD="java"
fi

$JCMD -server -cp $CLJSC_CP clojure.main -e \
"(require '[cljs.lua.repl :as repl])
(repl/-main)"
