#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/."
fi

CLJSC_CP=''
for next in $DIR/../lib/* $DIR/../src $DIR/../libclojurescript.jar; do
    CLJSC_CP=$CLJSC_CP:$next
done

java -server -cp $CLJSC_CP clojure.main -e \
"(require '[cljs.lua.compiler :as comp])
(comp/-main)"
